#!/usr/bin/env python3
"""
Asset Migration Pipeline

Copies raw assets from raws/ to Remotion's public directory and generates
TypeScript files (resourceMap.ts, constants.ts, timing.ts).

Agent 只需在生成后 edit constants.ts 中的 COLORS 和 FONTS（从 memo.md 提取）。

Usage:
    python migrate_assets.py --project-path /path/to/project
    python migrate_assets.py --project-path /path/to/project --skip-copy
"""

import argparse
import json
import os
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import yaml
except ImportError:
    yaml = None


def load_yaml(path: str) -> Dict[str, Any]:
    """Load YAML file, with fallback if PyYAML not installed."""
    if yaml is None:
        print("Warning: PyYAML not installed, using JSON fallback", file=sys.stderr)
        json_path = path.replace('.yaml', '.json').replace('.yml', '.json')
        if Path(json_path).exists():
            with open(json_path, 'r', encoding='utf-8') as f:
                return json.load(f)
        raise ImportError("Install PyYAML: pip install pyyaml")

    with open(path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)


def copy_assets(raws_dir: str, public_dir: str) -> List[str]:
    """Copy all assets from raws to public directory."""
    copied = []
    raws_path = Path(raws_dir)
    public_path = Path(public_dir)
    public_path.mkdir(parents=True, exist_ok=True)

    for root, dirs, files in os.walk(raws_path):
        dirs[:] = [d for d in dirs if not d.startswith('.')]
        for file in files:
            if file.startswith('.') or file.endswith('.DS_Store'):
                continue
            # Skip non-asset files
            if file.endswith(('.json', '.yaml', '.yml', '.md', '.txt', '.pdf')):
                continue

            src = Path(root) / file
            rel_path = src.relative_to(raws_path)
            dst = public_path / rel_path
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(str(src), str(dst))
            copied.append(str(rel_path))

    return copied


def generate_resource_map(
    resources: Optional[Dict],
    durations: Optional[Dict],
    output_path: str,
    raws_dir: Optional[str] = None,
) -> None:
    """Generate resourceMap.ts from resources.yaml and actual files."""
    imports = [
        "import { staticFile } from 'remotion';",
    ]
    # durations.json import added conditionally below
    if durations:
        imports.append("import _durations from './durations.json';")

    lines = [
        '// Auto-generated by migrate_assets.py — do not edit manually',
        *imports,
        '',
    ]

    # Visual resources from resources.yaml
    visuals = []
    audios = []
    if resources:
        for item in resources.get('resources', {}).get('visual', []):
            visuals.append(item)
        for item in resources.get('resources', {}).get('audio', []):
            audios.append(item)

    # Images — scan actual files
    if raws_dir:
        images_dir = Path(raws_dir) / 'images'
        if images_dir.is_dir():
            image_files = sorted(
                f for f in images_dir.rglob('*')
                if f.is_file() and not f.name.startswith('.')
                and f.suffix.lower() not in ('.json', '.yaml', '.yml', '.md', '.txt', '.pdf')
            )
            if image_files:
                lines.append('// Image resources')
                lines.append('export const IMAGES = {')
                seen_keys = set()
                for f in image_files:
                    rel = f.relative_to(Path(raws_dir))
                    key = f.stem.replace('-', '_').replace(' ', '_').replace('.', '_')
                    if key in seen_keys:
                        print(f"Warning: duplicate image key '{key}' from {f.name}, skipping", file=sys.stderr)
                        continue
                    seen_keys.add(key)
                    lines.append(f"  {key}: staticFile('{rel}'),")
                lines.append('} as const;')
                lines.append('')

    # Voiceover resources
    if durations:
        lines.append('// Voiceover resources')
        lines.append('export const VOICEOVER = {')
        for vo_id in sorted(durations.keys()):
            path = f'audio/vo/{vo_id}.wav'
            lines.append(f"  {vo_id}: staticFile('{path}'),")
        lines.append('} as const;')
        lines.append('')

        lines.append('// Voiceover durations — imported from durations.json (single source of truth)')
        lines.append('export const VO_DURATIONS = _durations as Record<keyof typeof VOICEOVER, number>;')
        lines.append('')

    # BGM resources
    bgm_files = []
    if raws_dir:
        bgm_dir = Path(raws_dir) / 'audio' / 'bgm'
        if bgm_dir.is_dir():
            bgm_files = sorted(
                f for f in bgm_dir.iterdir()
                if f.is_file() and not f.name.startswith('.')
            )
    if bgm_files:
        lines.append('// BGM resources')
        lines.append('export const BGM = {')
        for f in bgm_files:
            key = f.stem.replace('-', '_').replace(' ', '_')
            lines.append(f"  {key}: staticFile('audio/bgm/{f.name}'),")
        lines.append('} as const;')
        lines.append('')

    # SFX resources
    sfx_files = []
    if raws_dir:
        sfx_dir = Path(raws_dir) / 'audio' / 'sfx'
        if sfx_dir.is_dir():
            sfx_files = sorted(
                f for f in sfx_dir.iterdir()
                if f.is_file() and not f.name.startswith('.')
            )
    if sfx_files:
        lines.append('// SFX resources')
        lines.append('export const SFX = {')
        for f in sfx_files:
            key = f.stem.replace('-', '_').replace(' ', '_')
            lines.append(f"  {key}: staticFile('audio/sfx/{f.name}'),")
        lines.append('} as const;')
        lines.append('')

    # Video resources — scan actual files
    video_files = []
    if raws_dir:
        for vdir_name in ('videos', 'video'):
            vdir = Path(raws_dir) / vdir_name
            if vdir.is_dir():
                video_files = sorted(
                    f for f in vdir.rglob('*')
                    if f.is_file() and not f.name.startswith('.')
                    and f.suffix.lower() not in ('.json', '.yaml', '.yml', '.md', '.txt', '.pdf')
                )
                break
    if video_files and raws_dir:
        lines.append('// Video resources')
        lines.append('export const VIDEO = {')
        seen_keys = set()
        for f in video_files:
            rel = f.relative_to(Path(raws_dir))
            key = f.stem.replace('-', '_').replace(' ', '_').replace('.', '_')
            if key in seen_keys:
                print(f"Warning: duplicate video key '{key}' from {f.name}, skipping", file=sys.stderr)
                continue
            seen_keys.add(key)
            lines.append(f"  {key}: staticFile('{rel}'),")
        lines.append('} as const;')
        lines.append('')

    # Type exports
    lines.append('// Type exports')
    lines.append('export type ImageKey = keyof typeof IMAGES;')
    if durations:
        lines.append('export type VoiceoverKey = keyof typeof VOICEOVER;')
    if bgm_files:
        lines.append('export type BgmKey = keyof typeof BGM;')
    if sfx_files:
        lines.append('export type SfxKey = keyof typeof SFX;')
    if video_files:
        lines.append('export type VideoKey = keyof typeof VIDEO;')
    lines.append('')

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))


def generate_constants(output_path: str) -> None:
    """Generate constants.ts with defaults. Agent should edit COLORS and FONTS from memo.md."""
    content = '''\
// Auto-generated by migrate_assets.py
// TODO: Agent 需要从 memo.md 提取实际配色替换 COLORS，提取字体替换 FONTS

// ── Video Specifications ──
export const VIDEO_CONFIG = {
  width: 1920,
  height: 1080,
  fps: 30,
} as const;

export const FPS = VIDEO_CONFIG.fps;

// ── Color Palette (Agent: 从 memo.md 替换) ──
export const COLORS = {
  primary: '#3B82F6',
  secondary: '#10B981',
  accent: '#8B5CF6',

  bgDark: '#0F172A',
  bgLight: '#F8FAFC',
  flatGray: '#F1F5F9',
  flatBlue: '#DBEAFE',
  flatGreen: '#DCFCE7',
  flatYellow: '#FEF3C7',
  flatRed: '#FEE2E2',

  textDark: '#020617',
  textPrimary: '#0F172A',
  textSecondary: '#334155',
  textLight: '#F8FAFC',
  textMuted: '#94A3B8',

  success: '#22C55E',
  warning: '#F59E0B',
  error: '#EF4444',
  info: '#3B82F6',
} as const;

// ── Typography (Agent: 从 memo.md 替换) ──
export const FONTS = {
  primary: 'Inter, system-ui, sans-serif',
  mono: 'JetBrains Mono, monospace',
  display: 'Plus Jakarta Sans, sans-serif',
} as const;

// ── Font Sizes (1080p standard) ──
export const FONT_SIZES = {
  title: 72,
  subtitle: 48,
  heading: 36,
  body: 24,
  caption: 18,
  code: 20,
} as const;

// ── Pacing (storyboard pacing → animation speed multiplier) ──
export const PACING = {
  slow: 0.6,
  medium: 1.0,
  fast: 1.5,
  pause: 0.3,
} as const;

// ── Tension → Spring Animation Config ──
export const TENSION_CONFIG = {
  low: { damping: 25, stiffness: 80 },
  medium: { damping: 15, stiffness: 150 },
  high: { damping: 8, stiffness: 250 },
  extreme: { damping: 5, stiffness: 350 },
} as const;
'''
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)



def generate_timing(output_path: str) -> None:
    """Generate timing.ts with all frame calculation utilities."""
    content = '''\
// Auto-generated by migrate_assets.py — do not edit manually
import { VO_DURATIONS } from './resourceMap';
import { FPS } from './constants';

/**
 * Convert seconds to frames (always integer)
 */
export function secToFrames(sec: number): number {
  return Math.round(sec * FPS);
}

/**
 * Convert milliseconds to frames (always integer)
 */
export function msToFrames(ms: number): number {
  return Math.round((ms / 1000) * FPS);
}

/**
 * Ensure minimum 1-frame duration (prevents interpolate errors)
 */
export function safeDuration(frames: number): number {
  return Math.max(frames, 1);
}

/**
 * Calculate shot duration from voiceover references
 */
export function calculateShotDuration(
  voIds: (keyof typeof VO_DURATIONS)[],
  bufferMs = 700
): number {
  const totalVoMs = voIds.reduce((sum, id) => sum + (VO_DURATIONS[id] || 0), 0);
  return msToFrames(totalVoMs + bufferMs);
}

/**
 * Calculate cumulative start frame for a shot
 */
export function calculateShotStart(
  shotIndex: number,
  shotDurations: number[]
): number {
  return shotDurations.slice(0, shotIndex).reduce((sum, d) => sum + d, 0);
}

/**
 * Get animation speed multiplier from storyboard pacing
 */
export function pacingMultiplier(pacing: 'slow' | 'medium' | 'fast' | 'pause'): number {
  const map = { slow: 0.6, medium: 1.0, fast: 1.5, pause: 0.3 };
  return map[pacing] ?? 1.0;
}

/**
 * Convert visual_tension (0-1) to spring animation config
 */
export function tensionToSpringConfig(tension: number): { damping: number; stiffness: number } {
  const damping = Math.round(25 - tension * 20);  // 25→5
  const stiffness = Math.round(80 + tension * 270); // 80→350
  return { damping: Math.max(5, damping), stiffness };
}

/**
 * Calculate audio offset in frames from audio_visual_relation
 */
export function audioOffsetFrames(
  relation: 'sync' | 'lead-visual' | 'lead-audio' | 'counterpoint',
  fps: number,
  offsetMs?: number,
): number {
  if (relation === 'sync' || relation === 'counterpoint') return 0;
  const defaultMs = relation === 'lead-visual' ? 500 : -300;
  return Math.round((offsetMs ?? defaultMs) / 1000 * fps);
}
'''
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)



def main():
    parser = argparse.ArgumentParser(description="Migrate assets and generate TypeScript files")
    parser.add_argument("--project-path", required=True, help="Project root directory")
    parser.add_argument("--raws", default="raws", help="Raw assets dir (relative to project-path)")
    parser.add_argument("--public", default="template-project/public", help="Remotion public dir")
    parser.add_argument("--resources", default="manifests/resources.yaml", help="resources.yaml path")
    parser.add_argument("--durations", default="raws/audio/vo/durations.json", help="durations.json path")
    parser.add_argument("--output-dir", default="template-project/src/lib", help="TypeScript output dir")
    parser.add_argument("--skip-copy", action="store_true", help="Skip asset copy, only generate TS")

    args = parser.parse_args()
    project = Path(args.project_path)

    try:
        # Step 1: Copy assets
        if not args.skip_copy:
            raws_dir = project / args.raws
            public_dir = project / args.public
            if not raws_dir.is_dir():
                print(f"Error: raws directory not found: {raws_dir}", file=sys.stderr)
                sys.exit(1)
            copied = copy_assets(str(raws_dir), str(public_dir))
            images = [f for f in copied if f.startswith('images/')]
            audio = [f for f in copied if f.startswith('audio/')]
            videos = [f for f in copied if f.startswith('video')]
            print(f"Copied: {len(images)} images, {len(audio)} audio, {len(videos)} videos")

        # Step 2: Load resources.yaml
        resources = None
        res_path = Path(args.resources) if Path(args.resources).is_absolute() else project / args.resources
        if res_path.exists():
            resources = load_yaml(str(res_path))

        # Step 3: Load durations.json
        durations = None
        dur_path = Path(args.durations) if Path(args.durations).is_absolute() else project / args.durations
        if dur_path.exists():
            with open(dur_path, 'r', encoding='utf-8') as f:
                durations = json.load(f)
        else:
            print(f"Warning: {dur_path} not found", file=sys.stderr)

        # Step 4: Generate TypeScript files
        output_dir = project / args.output_dir

        generate_resource_map(resources, durations, str(output_dir / "resourceMap.ts"), raws_dir=str(project / args.raws))
        generate_constants(str(output_dir / "constants.ts"))
        generate_timing(str(output_dir / "timing.ts"))

        # Copy durations.json to src/lib/ for direct import
        if durations and dur_path.exists():
            dst_dur = output_dir / "durations.json"
            shutil.copy2(str(dur_path), str(dst_dur))

        # Summary
        parts = ["resourceMap.ts", "constants.ts", "timing.ts"]
        if durations:
            total_ms = sum(durations.values())
            parts.append(f"durations.json ({len(durations)} VOs, {total_ms/1000:.0f}s)")
        print("Output dir: ", output_dir)
        print(f"Generated: {', '.join(parts)}")
        print("REMIND: EDIT constants.ts (COLORS & FONTS from memo.md), then `npx tsc --noEmit`")

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
